first commit

diff --git a/.github/workflows/linters.yml b/.github/workflows/linters.yml
--- a/.github/workflows/linters.yml
+++ b/.github/workflows/linters.yml
@@ -1,70 +1,59 @@
-name: Linters
+#/bin/bash
 
-on: pull_request
+base_url="https://raw.githubusercontent.com/microverseinc/linters-config"
+branch="master"
+usage="
+Usage: check-linters-config dir
 
-env:
-  FORCE_COLOR: 1
+Please provide a valid dir to compare againts.
 
-jobs:
-  lighthouse:
-    name: Lighthouse
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-node@v1
-        with:
-          node-version: "12.x"
-      - name: Setup Lighthouse
-        run: npm install -g @lhci/cli@0.7.x
-      - name: Lighthouse Report
-        run: lhci autorun --upload.target=temporary-public-storage --collect.staticDistDir=.
-  webhint:
-    name: Webhint
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-node@v1
-        with:
-          node-version: "12.x"
-      - name: Setup Webhint
-        run: |
-          npm install --save-dev hint@7.x
-          [ -f .hintrc ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/html-css-js/.hintrc
-      - name: Webhint Report
-        run: npx hint .
-  stylelint:
-    name: Stylelint
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-node@v1
-        with:
-          node-version: "12.x"
-      - name: Setup Stylelint
-        run: |
-          npm install --save-dev stylelint@13.x stylelint-scss@3.x stylelint-config-standard@21.x stylelint-csstree-validator@1.x
-          [ -f .stylelintrc.json ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/html-css-js/.stylelintrc.json
-      - name: Stylelint Report
-        run: npx stylelint "**/*.{css,scss}"
-  eslint:
-    name: ESLint
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-node@v1
-        with:
-          node-version: "12.x"
-      - name: Setup ESLint
-        run: |
-          npm install --save-dev eslint@7.x eslint-config-airbnb-base@14.x eslint-plugin-import@2.x babel-eslint@10.x
-          [ -f .eslintrc.json ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/html-css-js/.eslintrc.json
-      - name: ESLint Report
-        run: npx eslint .
-  nodechecker:
-    name: node_modules checker
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v2
-      - name: Check node_modules existence
-        run: |
-          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set up a .gitignore file with this folder included on it to prevent this from happening in the future." && exit 1; fi
+Valid options for dir:
+  html-css
+  javascript
+  react-redux
+  ror
+  ruby
+
+Example: check-linters-config ruby
+"
+
+compare () {
+  directory="$1"
+  config_files="$2"
+  for file in "${config_files[@]}"; do
+    if [ -f "${file}" ]; then
+      original_file="${branch}/${directory}/${file}"
+      wget -qO- "${base_url}/${original_file}" |
+      diff \
+        --brief \
+        --report-identical-files \
+        --ignore-all-space \
+        --ignore-blank-lines \
+        --strip-trailing-cr \
+        --label="${original_file}" \
+        - "${file}"
+    else
+      echo "File '${file}' is missing"
+    fi
+  done
+}
+
+case $1 in
+  html-css)
+  config_files=(".hintrc" ".stylelintrc.json")
+  ;;
+  ruby)
+  config_files=(".rubocop.yml")
+  ;;
+  ror)
+  config_files=(".stylelintrc.json" ".rubocop.yml")
+  ;;
+  javascript | react-redux)
+  config_files=(".stylelintrc.json" ".eslintrc.json")
+  ;;
+  *)
+  echo "$usage"
+  exit 1
+esac
+
+compare "$1" "${config_files[@]}"
